# Generated by Django 4.2.7 on 2026-04-28 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='الرمز')),
                ('icon', models.CharField(blank=True, default='fa-tag', max_length=50, verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='items.category', verbose_name='التصنيف الرئيسي')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'db_table': 'item_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=300, verbose_name='اسم المنتج')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='الاسم بالإنجليزية')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='رمز المنتج (SKU)')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='الباركود')),
                ('item_type', models.CharField(choices=[('product', 'منتج'), ('service', 'خدمة'), ('raw_material', 'مادة خام'), ('semi_finished', 'منتج نصف مصنع')], default='product', max_length=20, verbose_name='نوع الصنف')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='سعر التكلفة')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='سعر البيع')),
                ('min_selling_price', models.DecimalField(decimal_places=2, default=0, help_text='أقل سعر يُسمح بالبيع به', max_digits=14, verbose_name='الحد الأدنى للسعر')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة %')),
                ('min_quantity', models.DecimalField(decimal_places=4, default=0, help_text='يُنبّه عند الوصول لهذه الكمية', max_digits=12, verbose_name='الحد الأدنى للمخزون')),
                ('max_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='الحد الأقصى للمخزون')),
                ('track_expiry', models.BooleanField(default=False, verbose_name='تتبع تاريخ الانتهاء')),
                ('track_batch', models.BooleanField(default=False, verbose_name='تتبع رقم الدفعة / الباتش')),
                ('track_serial', models.BooleanField(default=False, verbose_name='تتبع الرقم التسلسلي')),
                ('has_variants', models.BooleanField(default=False, verbose_name='يحتوي على متغيرات (مقاسات/ألوان)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='صورة المنتج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_sellable', models.BooleanField(default=True, verbose_name='قابل للبيع')),
                ('is_purchasable', models.BooleanField(default=True, verbose_name='قابل للشراء')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.category', verbose_name='التصنيف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'db_table': 'items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوحدة')),
                ('abbreviation', models.CharField(blank=True, max_length=20, verbose_name='الاختصار')),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=1, help_text='كم وحدة أساسية تُعادل هذه الوحدة؟ مثال: كرتون = 12 قطعة', max_digits=10, verbose_name='عامل التحويل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='items.unit', verbose_name='الوحدة الأساسية')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'وحدة قياس',
                'verbose_name_plural': 'وحدات القياس',
                'db_table': 'item_units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(help_text='مثال: أبيض - L', max_length=200, verbose_name='اسم المتغير')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='الباركود')),
                ('sku_suffix', models.CharField(blank=True, help_text='تُضاف لـ SKU الأصل، مثال: -WL', max_length=20, verbose_name='لاحقة الرمز')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='+ يعني أغلى، - يعني أرخص من الأصل', max_digits=10, verbose_name='فرق السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='items.item', verbose_name='المنتج الأساسي')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'متغير منتج',
                'verbose_name_plural': 'متغيرات المنتجات',
                'db_table': 'item_variants',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='items.unit', verbose_name='وحدة الشراء'),
        ),
        migrations.AddField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.unit', verbose_name='وحدة البيع'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['tenant', 'is_active'], name='item_units_tenant__2209b2_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvariant',
            index=models.Index(fields=['tenant', 'item'], name='item_varian_tenant__6f1cba_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'is_active'], name='items_tenant__03b56f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'barcode'], name='items_tenant__25dbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'category'], name='items_tenant__5bc68e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'name'], name='items_tenant__aed2d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('tenant', 'sku')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'is_active'], name='item_catego_tenant__153b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'parent'], name='item_catego_tenant__386ef2_idx'),
        ),
    ]
