# Generated by Django 4.2.7 on 2026-06-01 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_tenant_currency'),
        ('items', '0002_bomrecipe_bomline_itembatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_multiple_units',
            field=models.BooleanField(default=False, verbose_name='وحدات متعددة'),
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الوحدة')),
                ('factor', models.DecimalField(decimal_places=4, default=1, help_text='الكمية بالنسبة للوحدة الأصغر — الوحدة الأصغر دائماً = 1', max_digits=10, verbose_name='العامل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_units', to='items.item', verbose_name='المنتج')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'وحدة المنتج',
                'db_table': 'item_product_units',
                'ordering': ['factor'],
                'indexes': [models.Index(fields=['tenant', 'item'], name='item_produc_tenant__ddb883_idx')],
                'unique_together': {('item', 'name')},
            },
        ),
    ]
