# Generated by Django 4.2.7 on 2026-06-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_saleinvoiceline_variant_and_more'),
        ('items', '0006_add_color_size_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='size',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='size',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='size',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='has_variants',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='ItemVariant',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
