# Generated by Django 4.2.7 on 2026-06-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_remove_itemvariant_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.itemunit', verbose_name='الوحدة'),
        ),
    ]
