# Generated by Django 4.2.7 on 2026-06-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_bom_line_unit_fk_to_itemunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_price_hc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='سعر التكلفة بالعملة الصعبة'),
        ),
        migrations.AddField(
            model_name='item',
            name='min_selling_price_hc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='الحد الأدنى بالعملة الصعبة'),
        ),
        migrations.AddField(
            model_name='item',
            name='selling_price_hc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='سعر البيع بالعملة الصعبة'),
        ),
    ]
