# Generated by Django 4.2.7 on 2026-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_cost_price_hc_item_min_selling_price_hc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alternatives',
            field=models.ManyToManyField(blank=True, help_text='أصناف يمكن اقتراحها كبديل عند نفاد هذا الصنف', to='items.item', verbose_name='بدائل / أصناف مكافئة'),
        ),
        migrations.AddField(
            model_name='item',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='مثال: أقراص، شراب، حقن، كبسولات', max_length=100, verbose_name='الشكل الصيدلاني'),
        ),
        migrations.AddField(
            model_name='item',
            name='generic_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='الاسم العلمي / المادة الفعالة'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_controlled_substance',
            field=models.BooleanField(default=False, verbose_name='خاضع للرقابة / مخدرات'),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='الشركة المصنعة'),
        ),
        migrations.AddField(
            model_name='item',
            name='requires_prescription',
            field=models.BooleanField(default=False, verbose_name='يُصرف بوصفة طبية'),
        ),
        migrations.AddField(
            model_name='item',
            name='strength',
            field=models.CharField(blank=True, help_text='مثال: 500 مجم، 5 مل', max_length=100, verbose_name='التركيز'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'is_controlled_substance'], name='items_tenant__82cb28_idx'),
        ),
    ]
