# Generated by Django 4.2.7 on 2026-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_item_alternatives_item_dosage_form_item_generic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_insurance_excluded',
            field=models.BooleanField(default=False, help_text='يُستبعد تلقائياً عند إنشاء مطالبة تأمين لفاتورة تحتوي هذا الصنف', verbose_name='غير مغطى بالتأمين'),
        ),
    ]
