# Generated by Django 5.0.6 on 2026-09-15 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0026_alter_platformsettings_platform_name'),
        ('items', '0011_item_is_insurance_excluded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='master_drug',
            field=models.ForeignKey(blank=True, help_text='يُملأ تلقائياً عند إنشاء الصنف من الكتالوج الرئيسي — يُستخدم لاقتراح البدائل تلقائياً', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_items', to='catalog.masterdrug', verbose_name='مرتبط بالكتالوج الرئيسي'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'generic_name', 'dosage_form', 'strength'], name='items_tenant__9f3251_idx'),
        ),
    ]
