# Generated by Django 5.0.6 on 2026-09-15 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_masterdrug_description_masterdrug_image_and_more'),
        ('core', '0026_alter_platformsettings_platform_name'),
        ('items', '0012_item_master_drug_item_items_tenant__9f3251_idx'),
        ('suppliers', '0004_supplier_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='الشركة/المورد الذي يوفر هذا الصنف — يُستخدم للتصفية، وهو غير الشركة المصنعة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_items', to='suppliers.supplier', verbose_name='الشركة الموردة'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'supplier'], name='items_tenant__a6d231_idx'),
        ),
    ]
