# Generated by Django 5.0.6 on 2026-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_supplier_item_items_tenant__a6d231_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='بلد المنشأ'),
        ),
        migrations.AddField(
            model_name='item',
            name='pack_size',
            field=models.CharField(blank=True, max_length=300, verbose_name='حجم العبوة'),
        ),
        migrations.AddField(
            model_name='item',
            name='sudan_agent',
            field=models.CharField(blank=True, max_length=200, verbose_name='الوكيل أو الموزع في السودان'),
        ),
    ]
