# Generated by Django 4.2.7 on 2026-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_item_country_of_origin_item_pack_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='track_batch',
            field=models.BooleanField(default=False, verbose_name='تتبع رقم الدفعة'),
        ),
    ]
