# Generated by Django 4.2.7 on 2026-04-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('customers', '0002_add_sale_quote'),
        ('stocks', '0003_stock_is_system_default_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('quote_number', models.CharField(blank=True, help_text='يُولَّد تلقائياً بصيغة QUO-000001', max_length=20, verbose_name='رقم العرض')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='رقم مرجعي خارجي')),
                ('quote_date', models.DateField(verbose_name='تاريخ العرض')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مُرسَل'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('converted', 'مُحوَّل لفاتورة'), ('expired', 'منتهي الصلاحية'), ('cancelled', 'ملغى')], default='draft', max_length=15, verbose_name='الحالة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المجموع قبل الخصم')),
                ('quote_discount_type', models.CharField(choices=[('percent', 'نسبة مئوية'), ('amount', 'مبلغ ثابت')], default='percent', max_length=10, verbose_name='نوع الخصم الإجمالي')),
                ('quote_discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الخصم الإجمالي')),
                ('quote_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ الخصم الإجمالي')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الضريبة')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي النهائي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('terms', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التحويل')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_quotes', to=settings.AUTH_USER_MODEL, verbose_name='حُوِّل بواسطة')),
                ('converted_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='sales.saleinvoice', verbose_name='الفاتورة المُحوَّلة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_quotes', to='customers.customer', verbose_name='العميل')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_quotes', to='stocks.stock', verbose_name='المخزن')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'db_table': 'sale_quotes',
                'ordering': ['-quote_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الوحدة')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='خصم السطر %')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ خصم السطر')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ الضريبة')),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مجموع السطر قبل الضريبة')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مجموع السطر (شامل الضريبة)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='items.item', verbose_name='المنتج')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_lines', to='sales.salequote', verbose_name='عرض السعر')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='items.itemvariant', verbose_name='المتغير')),
            ],
            options={
                'verbose_name': 'بند عرض سعر',
                'verbose_name_plural': 'بنود عروض الأسعار',
                'db_table': 'sale_quote_lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='salequote',
            index=models.Index(fields=['tenant', 'status'], name='sale_quotes_tenant__f21bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='salequote',
            index=models.Index(fields=['tenant', 'customer'], name='sale_quotes_tenant__112733_idx'),
        ),
        migrations.AddIndex(
            model_name='salequote',
            index=models.Index(fields=['tenant', 'quote_date'], name='sale_quotes_tenant__84b624_idx'),
        ),
        migrations.AddIndex(
            model_name='salequote',
            index=models.Index(fields=['tenant', 'quote_number'], name='sale_quotes_tenant__adc71a_idx'),
        ),
    ]
