# Generated by Django 4.2.7 on 2026-05-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_bomrecipe_bomline_itembatch'),
        ('sales', '0002_add_sale_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoiceline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='items.unit', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='saleinvoiceline',
            name='unit_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='1 وحدة مستخدمة = unit_factor وحدة أساسية', max_digits=10, verbose_name='معامل التحويل'),
        ),
    ]
