# Generated by Django 4.2.7 on 2026-05-22 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_saleinvoiceline_unit_saleinvoiceline_unit_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_invoices', to=settings.AUTH_USER_MODEL, verbose_name='سُلِّمت بواسطة'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='delivery_type',
            field=models.CharField(choices=[('immediate', 'تسليم فوري'), ('deferred', 'تسليم لاحق')], default='immediate', max_length=10, verbose_name='نوع التسليم'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending_delivery', 'قيد التسليم'), ('confirmed', 'مؤكدة'), ('cancelled', 'ملغاة'), ('returned', 'مرتجعة كلياً'), ('partially_returned', 'مرتجعة جزئياً')], default='draft', max_length=25, verbose_name='الحالة'),
        ),
    ]
