# Generated by Django 4.2.7 on 2026-06-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_customerledger_tenant_alter_saleinvoice_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoiceline',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='salequoteline',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='variant',
        ),
    ]
