# Generated by Django 4.2.7 on 2026-06-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_saleinvoiceline_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='is_reversal',
            field=models.BooleanField(default=False, verbose_name='قيد عكسي'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='is_reversal',
            field=models.BooleanField(default=False, verbose_name='قيد عكسي'),
        ),
    ]
