# Generated by Django 4.2.7 on 2026-06-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_add_is_reversal_to_movements_and_ledgers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale_out', 'بيع — خروج'), ('sale_return_in', 'مرتجع بيع — دخول'), ('purchase_in', 'شراء — دخول'), ('purchase_return_out', 'مرتجع شراء — خروج'), ('transfer_in', 'تحويل — دخول'), ('transfer_out', 'تحويل — خروج'), ('adjustment_in', 'تسوية — دخول'), ('adjustment_out', 'تسوية — خروج'), ('opening_in', 'رصيد افتتاحي'), ('opening_correction', 'تصحيح رصيد افتتاحي')], max_length=25, verbose_name='نوع الحركة'),
        ),
    ]
