# Generated by Django 4.2.7 on 2026-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_opening_quantity_and_correction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='hc_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ بالعملة الصعبة'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='hc_currency',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='رمز العملة الصعبة'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='hc_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='سعر الصرف المستخدم'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='hc_running_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='الرصيد التراكمي بالعملة الصعبة'),
        ),
    ]
