# Generated by Django 4.2.7 on 2026-06-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('sales', '0009_add_hc_fields_to_ledgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_invoices', to='agents.agent', verbose_name='المندوب'),
        ),
    ]
