# Generated by Django 4.2.7 on 2026-09-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_saleinvoice_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقداً'), ('bank', 'تحويل بنكي'), ('insurance', 'شركة تأمين')], max_length=10, verbose_name='طريقة الدفع'),
        ),
    ]
