# Generated by Django 4.2.7 on 2026-09-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_salepayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale_out', 'بيع — خروج'), ('sale_return_in', 'مرتجع بيع — دخول'), ('purchase_in', 'شراء — دخول'), ('purchase_return_out', 'مرتجع شراء — خروج'), ('transfer_in', 'تحويل — دخول'), ('transfer_out', 'تحويل — خروج'), ('adjustment_in', 'تسوية — دخول'), ('adjustment_out', 'تسوية — خروج'), ('opening_in', 'رصيد افتتاحي'), ('opening_correction', 'تصحيح رصيد افتتاحي'), ('destruction_out', 'إتلاف — خروج')], max_length=25, verbose_name='نوع الحركة'),
        ),
    ]
