# Generated by Django 4.2.7 on 2026-09-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المتوقع من التأمين (مختلط)'),
        ),
    ]
