# Generated by Django 4.2.7 on 2026-09-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insurancemember_remove_insuranceclaim_policy_and_more'),
        ('sales', '0013_saleinvoice_insurance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='insurance_card_number',
            field=models.CharField(blank=True, help_text='لقطة من رقم البطاقة وقت البيع', max_length=100, verbose_name='رقم بطاقة التأمين وقت البيع'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='insurance_member',
            field=models.ForeignKey(blank=True, help_text='المؤمَّن عليه (صاحب البطاقة) لبيع بالتأمين — مستقل تماماً عن العميل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_invoices', to='insurance.insurancemember', verbose_name='المؤمَّن عليه'),
        ),
    ]
