# Generated by Django 4.2.7 on 2026-09-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('sales', '0014_saleinvoice_insurance_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='الحساب البنكي المستلِم للجزء البنكي من الفاتورة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoices', to='bank_accounts.bankaccount', verbose_name='الحساب البنكي'),
        ),
    ]
