# Generated by Django 4.2.7 on 2026-09-14 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_item_is_insurance_excluded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_alter_platformsettings_platform_name'),
        ('sales', '0015_saleinvoice_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoiceLineBatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('batch_number_snapshot', models.CharField(blank=True, max_length=100, verbose_name='رقم الدفعة')),
                ('expiry_date_snapshot', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية القائمة')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_allocations', to='items.itembatch', verbose_name='الدفعة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='sales.saleinvoiceline', verbose_name='سطر الفاتورة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'تخصيص دفعة لبند فاتورة',
                'verbose_name_plural': 'تخصيصات الدفعات لبنود الفواتير',
                'db_table': 'sale_invoice_line_batch_allocations',
            },
        ),
        migrations.CreateModel(
            name='SaleReturnLineBatchRestoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية المُعادة')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_restorations', to='items.itembatch', verbose_name='الدفعة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('return_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_restorations', to='sales.salereturnline', verbose_name='سطر المرتجع')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'إعادة دفعة لبند مرتجع',
                'verbose_name_plural': 'إعادات الدفعات لبنود المرتجعات',
                'db_table': 'sale_return_line_batch_restorations',
                'indexes': [models.Index(fields=['tenant', 'return_line'], name='sale_return_tenant__ff8fa9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='salereturnlinebatchrestoration',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='sale_return_line_batch_restore_qty_gt_0'),
        ),
        migrations.AddIndex(
            model_name='saleinvoicelinebatchallocation',
            index=models.Index(fields=['tenant', 'sale_line'], name='sale_invoic_tenant__26a4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='saleinvoicelinebatchallocation',
            index=models.Index(fields=['tenant', 'batch'], name='sale_invoic_tenant__97b77a_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleinvoicelinebatchallocation',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='sale_line_batch_alloc_qty_gt_0'),
        ),
    ]
