# Generated by Django 4.2.7 on 2026-09-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_platformsettings_platform_name'),
        ('sales', '0016_saleinvoicelinebatchallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='الفرع المرتبط مباشرة بالفاتورة (enterprise فقط؛ يُملأ تلقائياً من المخزن إن لم يُحدد)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoices', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='الفرع المرتبط مباشرة بالمرتجع (enterprise فقط؛ يُملأ تلقائياً من الفاتورة الأصلية إن لم يُحدد)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='core.branch', verbose_name='الفرع'),
        ),
    ]
