# Generated by Django 4.2.7 on 2026-04-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_tenant__072105_idx',
            old_name='customers_cu_tenant__0ea6c0_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_tenant__a2831a_idx',
            old_name='customers_cu_tenant__faaf04_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_tenant__ac02c9_idx',
            old_name='customers_cu_tenant__f9fef1_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
    ]
