# Generated by Django 4.2.7 on 2026-05-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_add_sale_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='portal_token',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='رمز البوابة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='portal_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انتهاء رمز البوابة'),
        ),
    ]
