# Generated by Django 4.2.7 on 2026-06-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_settings_options_alter_tenant_options_and_more'),
        ('customers', '0003_customer_portal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
    ]
