# Generated by Django 4.2.7 on 2026-04-27 06:01

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='الصورة الشخصية')),
                ('role', models.CharField(choices=[('owner', 'مالك النشاط'), ('admin', 'مدير'), ('cashier', 'كاشير'), ('stock_keeper', 'أمين مخزن'), ('accountant', 'محاسب'), ('viewer', 'مشاهد فقط')], default='cashier', max_length=20, verbose_name='الدور الوظيفي')),
                ('is_tenant_admin', models.BooleanField(default=False, verbose_name='مدير النشاط')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل دخول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المجموعة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('permissions', models.JSONField(default=dict, verbose_name='الصلاحيات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مجموعة صلاحيات',
                'verbose_name_plural': 'مجموعات الصلاحيات',
                'db_table': 'permission_groups',
                'ordering': ['name'],
            },
        ),
    ]
