# Generated by Django 4.2.7 on 2026-06-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_settings_options_alter_tenant_options_and_more'),
        ('accounts', '0003_remove_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_groups', to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant', verbose_name='المشترك'),
        ),
    ]
