# Generated by Django 4.2.7 on 2026-06-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_permissiongroup_tenant_alter_user_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_staff',
            field=models.BooleanField(default=False, verbose_name='مساعد منصة'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='صلاحيات المنصة'),
        ),
    ]
