# Generated by Django 4.2.7 on 2026-06-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_activity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='user_activi_tenant__b9954f_idx',
            old_name='act_tenant_date_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='user_activi_tenant__dd989f_idx',
            old_name='act_tenant_user_date_idx',
        ),
    ]
