# Generated by Django 4.2.7 on 2026-09-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_platformsettings_platform_name'),
        ('accounts', '0007_rename_act_tenant_date_idx_user_activi_tenant__b9954f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.branch', verbose_name='الفرع'),
        ),
    ]
