# Generated by Django 4.2.7 on 2026-09-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_platformsettings_platform_name'),
        ('accounts', '0008_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to='core.branch', verbose_name='الفرع'),
        ),
    ]
