# Generated by Django 4.2.7 on 2026-09-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_useractivity_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_branch_supervisor',
            field=models.BooleanField(default=False, verbose_name='مشرف الفرع'),
        ),
    ]
