# Generated by Django 5.0.6 on 2026-09-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_restrict_enterprise_owner_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='scope',
            field=models.CharField(blank=True, choices=[('branch', 'فروع'), ('admin', 'إدارة النشاط')], default='', max_length=10, verbose_name='نطاق المجموعة'),
        ),
    ]
