# Generated by Django 5.0.6 on 2026-09-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_permissiongroup_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='is_owner_group',
            field=models.BooleanField(default=False, verbose_name='مجموعة مالك الاشتراك'),
        ),
    ]
