# Generated by Django 4.2.7 on 2026-05-31 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_tenant_currency'),
        ('items', '0002_bomrecipe_bomline_itembatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0004_add_delivery_type_and_pending_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('order_number', models.CharField(blank=True, max_length=30, verbose_name='رقم الطلب')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رمز التتبع')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('customer_address', models.TextField(blank=True, verbose_name='العنوان')),
                ('customer_notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('payment_method', models.CharField(choices=[('bank', 'تحويل بنكي'), ('credit', 'آجل')], max_length=10, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'تم القبول'), ('rejected', 'مرفوض')], default='pending', max_length=15, verbose_name='الحالة')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المجموع')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('sale_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_order', to='sales.saleinvoice', verbose_name='الفاتورة المُنشأة')),
            ],
            options={
                'verbose_name': 'طلب أونلاين',
                'verbose_name_plural': 'طلبات أونلاين',
                'db_table': 'store_online_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('slug', models.SlugField(help_text='يستخدم في عنوان المتجر مثال: my-shop', max_length=120, unique=True, verbose_name='رابط المتجر')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='المتجر مفعّل')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المتجر')),
                ('description', models.TextField(blank=True, verbose_name='وصف المتجر')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='store/covers/', verbose_name='صورة الغلاف')),
                ('accent_color', models.CharField(default='#6366f1', max_length=7, verbose_name='اللون الرئيسي')),
                ('whatsapp', models.CharField(blank=True, help_text='للتواصل السريع مع العملاء', max_length=30, verbose_name='واتساب (اختياري)')),
                ('show_out_of_stock', models.BooleanField(default=False, verbose_name='عرض المنتجات النافدة')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الحد الأدنى للطلب')),
                ('bank_details', models.TextField(blank=True, help_text='تظهر للعميل عند اختيار التحويل البنكي', verbose_name='بيانات التحويل البنكي')),
                ('delivery_message', models.TextField(blank=True, help_text='تظهر في صفحة تأكيد الطلب', verbose_name='رسالة الشحن/التسليم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'db_table': 'store_settings',
            },
        ),
        migrations.CreateModel(
            name='OnlineOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('item_name', models.CharField(max_length=300, verbose_name='اسم المنتج')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الوحدة')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الإجمالي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item', verbose_name='المنتج')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='store.onlineorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'بند طلب أونلاين',
                'db_table': 'store_online_order_lines',
            },
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.storesettings', verbose_name='المتجر'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='store_onlin_tenant__96efec_idx'),
        ),
        migrations.AddIndex(
            model_name='onlineorder',
            index=models.Index(fields=['token'], name='store_onlin_token_bfc711_idx'),
        ),
    ]
