# Generated by Django 4.2.7 on 2026-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='closed_message',
            field=models.CharField(blank=True, default='المتجر مغلق حالياً. يمكنك تصفح المنتجات وسنتواصل معك لاحقاً.', max_length=200, verbose_name='رسالة المغلق'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='open_message',
            field=models.CharField(blank=True, default='أهلاً! نحن مفتوحون الآن. يسعدنا خدمتك.', max_length=200, verbose_name='رسالة المفتوح'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='status_override',
            field=models.CharField(choices=[('auto', 'تلقائي (حسب الجدول)'), ('open', 'مفتوح دائماً'), ('closed', 'مغلق دائماً')], default='auto', max_length=10, verbose_name='حالة المتجر'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name='ساعات العمل'),
        ),
    ]
