# Generated by Django 4.2.7 on 2026-05-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storesettings_closed_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='show_prices',
            field=models.BooleanField(default=True, verbose_name='عرض الأسعار'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='show_stock_quantity',
            field=models.BooleanField(default=False, verbose_name='عرض الكمية المتوفرة'),
        ),
    ]
