# Generated by Django 4.2.7 on 2026-06-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_settings_options_alter_tenant_options_and_more'),
        ('store', '0003_storesettings_show_prices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='onlineorderline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='closed_message',
            field=models.CharField(blank=True, default='المتجر مغلق حالياً.', max_length=200, verbose_name='رسالة المغلق'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='open_message',
            field=models.CharField(blank=True, default='مرحباً بك .. المتجر مفتوح الآن', max_length=200, verbose_name='رسالة المفتوح'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
    ]
