# Generated by Django 4.2.7 on 2026-08-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_onlineorder_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='show_price_list',
            field=models.BooleanField(default=False, help_text='صفحة عامة منفصلة تعرض كل المنتجات وأسعارها مع بحث وفلترة، بدون طلب أو سلة', verbose_name='تفعيل قائمة الأسعار'),
        ),
    ]
