# Generated by Django 4.2.7 on 2026-09-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storesettings_show_price_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='accent_color',
            field=models.CharField(default='#c9840f', max_length=7, verbose_name='اللون الرئيسي'),
        ),
    ]
