# Generated by Django 4.2.7 on 2026-10-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_storesettings_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='price_list_columns',
            field=models.JSONField(blank=True, default=list, help_text='الأعمدة التي تظهر في قائمة الأسعار العامة. القائمة الفارغة = كل الأعمدة', verbose_name='أعمدة قائمة الأسعار'),
        ),
    ]
