# Generated by Django 4.2.7 on 2026-10-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_trial_days_14'),
        ('store', '0007_storesettings_price_list_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_orders', to='core.branch', verbose_name='الفرع'),
        ),
    ]
