# Generated by Django 4.2.7 on 2026-10-08 11:30

import apps.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_onlineorder_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='prescription',
            field=models.FileField(blank=True, help_text='اختياري: صورة أو ملف PDF للوصفة الطبية يرفقه الزبون', null=True, upload_to=apps.store.models.prescription_upload_path, verbose_name='الوصفة الطبية'),
        ),
        migrations.AddField(
            model_name='onlineorderline',
            name='requires_prescription',
            field=models.BooleanField(default=False, verbose_name='يُصرف بوصفة طبية'),
        ),
    ]
