# Generated by Django 4.2.7 on 2026-09-09 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0011_alter_salepayment_payment_method'),
        ('customers', '0005_alter_customer_opening_balance'),
        ('core', '0023_tenantcapabilities_has_branch_stock_lookup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('policy_number', models.CharField(blank=True, max_length=100, verbose_name='رقم البوليصة / العضوية')),
                ('coverage_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة التغطية %')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='سارية من')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='سارية حتى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'بوليصة تأمين عميل',
                'verbose_name_plural': 'بوليصات تأمين العملاء',
                'db_table': 'customer_insurance_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('claim_number', models.CharField(blank=True, max_length=20, verbose_name='رقم المطالبة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مُقدَّمة'), ('approved', 'معتمدة'), ('partially_approved', 'معتمدة جزئياً'), ('rejected', 'مرفوضة'), ('partially_paid', 'مسددة جزئياً'), ('paid', 'مسددة بالكامل'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('covered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المطالَب به')),
                ('patient_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='نصيب المريض')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ المعتمد')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المسدد فعلياً')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسوية المتوقع')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض/التخفيض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'مطالبة تأمين',
                'verbose_name_plural': 'مطالبات التأمين',
                'db_table': 'insurance_claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='الكود')),
                ('name', models.CharField(max_length=200, verbose_name='اسم شركة التأمين')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='مسؤول التواصل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('default_coverage_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة التغطية الافتراضية %')),
                ('settlement_period_days', models.PositiveIntegerField(default=30, verbose_name='مدة التسوية المتوقعة (يوم)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'شركة تأمين',
                'verbose_name_plural': 'شركات التأمين',
                'db_table': 'insurance_companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('entry_type', models.CharField(choices=[('opening', 'رصيد افتتاحي'), ('claim_submitted', 'مطالبة مُقدَّمة'), ('adjustment', 'تعديل اعتماد'), ('payment_received', 'دفعة مستلمة'), ('writeoff', 'شطب/رفض')], max_length=20, verbose_name='نوع القيد')),
                ('amount', models.DecimalField(decimal_places=2, help_text='موجب = مستحق لنا على شركة التأمين | سالب = تحصيل/تخفيض', max_digits=14, verbose_name='المبلغ')),
                ('entry_date', models.DateField(verbose_name='تاريخ القيد')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد التراكمي')),
                ('is_reversal', models.BooleanField(default=False, verbose_name='قيد عكسي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_entries', to='insurance.insuranceclaim', verbose_name='المطالبة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='insurance.insurancecompany', verbose_name='شركة التأمين')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'قيد تسوية تأمين',
                'verbose_name_plural': 'سجل تسويات التأمين',
                'db_table': 'insurance_ledger',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('coverage_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة التغطية %')),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المُطالَب به')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المبلغ المعتمد')),
                ('rejection_reason', models.CharField(blank=True, max_length=300, verbose_name='سبب الرفض')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='insurance.insuranceclaim', verbose_name='المطالبة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claim_lines', to='sales.saleinvoiceline', verbose_name='بند الفاتورة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'بند مطالبة تأمين',
                'verbose_name_plural': 'بنود مطالبات التأمين',
                'db_table': 'insurance_claim_lines',
            },
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='insurance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.insurancecompany', verbose_name='شركة التأمين'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claim', to='sales.saleinvoice', verbose_name='الفاتورة'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='insurance.customerinsurancepolicy', verbose_name='البوليصة'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_insurance_claims', to=settings.AUTH_USER_MODEL, verbose_name='قُدِّمت بواسطة'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='customerinsurancepolicy',
            name='insurance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance.insurancecompany', verbose_name='شركة التأمين'),
        ),
        migrations.AddField(
            model_name='customerinsurancepolicy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AddField(
            model_name='customerinsurancepolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddIndex(
            model_name='insurancecompany',
            index=models.Index(fields=['tenant', 'name'], name='insurance_c_tenant__cf15b9_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancecompany',
            index=models.Index(fields=['tenant', 'is_active'], name='insurance_c_tenant__d2fd66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='insurancecompany',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='insuranceclaimsettlement',
            index=models.Index(fields=['tenant', 'insurance_company', '-entry_date'], name='insurance_l_tenant__9f92eb_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaimsettlement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='insurance_l_referen_4c5e74_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['tenant', 'status'], name='insurance_c_tenant__ebec63_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['tenant', 'customer'], name='insurance_c_tenant__82f54e_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['tenant', 'insurance_company'], name='insurance_c_tenant__a162b7_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinsurancepolicy',
            index=models.Index(fields=['tenant', 'customer', 'is_active'], name='customer_in_tenant__ebfce0_idx'),
        ),
    ]
