# Generated by Django 4.2.7 on 2026-09-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_opening_balance'),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='customers.customer', verbose_name='العميل'),
        ),
    ]
