# Generated by Django 4.2.7 on 2026-09-12 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_alter_customer_opening_balance'),
        ('core', '0025_alter_tenant_subscription_plan'),
        ('insurance', '0002_alter_insuranceclaim_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('card_number', models.CharField(max_length=100, verbose_name='رقم البطاقة')),
                ('member_id', models.CharField(blank=True, max_length=100, verbose_name='رقم العضوية (إن وُجد على البطاقة)')),
                ('full_name', models.CharField(max_length=200, verbose_name='اسم المشترك')),
                ('coverage_percent', models.DecimalField(blank=True, decimal_places=2, help_text='تتجاوز نسبة الشركة الافتراضية لو حُدِّدت', max_digits=5, null=True, verbose_name='نسبة التغطية %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, help_text='اختياري — فقط لو الصيدلية عندها هذا الشخص مسجَّلاً كعميل لأسباب أخرى', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_memberships', to='customers.customer', verbose_name='العميل المرتبط')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='insurance.insurancecompany', verbose_name='شركة التأمين')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'مشترك تأمين',
                'verbose_name_plural': 'مشتركو التأمين',
                'db_table': 'insurance_members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='insuranceclaim',
            name='policy',
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='card_number',
            field=models.CharField(blank=True, help_text='لقطة من رقم البطاقة وقت البيع — تبقى ثابتة حتى لو البطاقة تغيّرت لاحقاً', max_length=100, verbose_name='رقم البطاقة وقت البيع'),
        ),
        migrations.DeleteModel(
            name='CustomerInsurancePolicy',
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='insurance.insurancemember', verbose_name='المؤمَّن عليه'),
        ),
        migrations.AddIndex(
            model_name='insurancemember',
            index=models.Index(fields=['tenant', 'insurance_company', 'is_active'], name='insurance_m_tenant__62cd5f_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancemember',
            index=models.Index(fields=['tenant', 'card_number'], name='insurance_m_tenant__fad7aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='insurancemember',
            unique_together={('tenant', 'card_number')},
        ),
    ]
