# Generated by Django 4.2.7 on 2026-04-27 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم بالإنجليزية')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('slug', models.SlugField(unique=True, verbose_name='الرمز')),
                ('icon', models.CharField(default='fa-store', max_length=50, verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='المميزات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'نوع نشاط تجاري',
                'verbose_name_plural': 'أنواع الأنشطة التجارية',
                'db_table': 'business_types',
                'ordering': ['display_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم النشاط التجاري')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرمز')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='الشعار')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='البلد')),
                ('subscription_plan', models.CharField(choices=[('trial', 'تجريبي'), ('basic', 'أساسي'), ('pro', 'احترافي'), ('enterprise', 'مؤسسات')], default='trial', max_length=20, verbose_name='الباقة')),
                ('subscription_start', models.DateField(default=django.utils.timezone.now, verbose_name='بداية الاشتراك')),
                ('subscription_expires', models.DateField(blank=True, null=True, verbose_name='نهاية الاشتراك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_demo', models.BooleanField(default=False, verbose_name='حساب تجريبي')),
                ('version_type', models.CharField(choices=[('single_store', 'محل واحد بمخزن واحد'), ('multi_stock', 'محل واحد بمخازن متعددة'), ('multi_branch', 'فروع متعددة (محلات ومخازن)')], default='single_store', max_length=20, verbose_name='نوع النسخة')),
                ('max_branches', models.IntegerField(default=1, verbose_name='عدد الفروع')),
                ('max_stocks', models.IntegerField(default=1, verbose_name='عدد المخازن')),
                ('max_users', models.IntegerField(default=5, verbose_name='عدد المستخدمين')),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=50, verbose_name='المنطقة الزمنية')),
                ('language', models.CharField(default='ar', max_length=10, verbose_name='اللغة')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='core.businesstype', verbose_name='نوع النشاط')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10, verbose_name='بادئة الفاتورة')),
                ('invoice_footer', models.TextField(blank=True, verbose_name='تذييل الفاتورة')),
                ('print_sale_invoice', models.BooleanField(default=True, verbose_name='طباعة فاتورة البيع')),
                ('print_purchase_invoice', models.BooleanField(default=True, verbose_name='طباعة فاتورة الشراء')),
                ('tax_enabled', models.BooleanField(default=False, verbose_name='تفعيل الضرائب')),
                ('tax_value', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='قيمة الضريبة %')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('show_zero_stock', models.BooleanField(default=True, verbose_name='إظهار منتجات بمخزون صفر')),
                ('low_stock_alert', models.BooleanField(default=True, verbose_name='تنبيه المخزون المنخفض')),
                ('items_per_page', models.IntegerField(default=25, verbose_name='عدد العناصر في الصفحة')),
                ('date_format', models.CharField(default='%Y-%m-%d', max_length=20, verbose_name='تنسيق التاريخ')),
                ('delete_password', models.CharField(default='delete123', max_length=100, verbose_name='كلمة مرور الحذف')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='إشعارات SMS')),
                ('custom_settings', models.JSONField(blank=True, default=dict, verbose_name='إعدادات مخصصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.tenant', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'إعدادات',
                'verbose_name_plural': 'إعدادات العملاء',
                'db_table': 'tenant_settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('view', 'عرض'), ('export', 'تصدير'), ('import', 'استيراد')], max_length=20, verbose_name='الإجراء')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='النموذج')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='معرف العنصر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.tenant', verbose_name='العميل')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات النشاطات',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_is_acti_ec1713_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant', '-created_at'], name='activity_lo_tenant__f92502_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx'),
        ),
    ]
