# Generated by Django 4.2.7 on 2026-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='currency',
            field=models.CharField(default='SDG', max_length=3, verbose_name='العملة'),
        ),
    ]
