# Generated by Django 4.2.7 on 2026-06-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_support_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسار الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='الحجم بالبايت')),
                ('backup_type', models.CharField(choices=[('manual', 'يدوي'), ('auto', 'تلقائي'), ('pre_restore', 'قبل الاسترداد')], default='manual', max_length=20, verbose_name='نوع النسخة')),
                ('status', models.CharField(choices=[('completed', 'مكتمل'), ('failed', 'فشل'), ('in_progress', 'جاري')], default='in_progress', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.tenant', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'النسخ الاحتياطية',
                'db_table': 'tenant_backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
