# Generated by Django 4.2.7 on 2026-06-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_backups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'إعدادات', 'verbose_name_plural': 'إعدادات المشتركين'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at'], 'verbose_name': 'مشترك', 'verbose_name_plural': 'المشتركين'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender_type',
            field=models.CharField(choices=[('tenant', 'المشترك'), ('admin', 'المشرف')], max_length=10, verbose_name='نوع المرسل'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='tenantbackup',
            name='backup_type',
            field=models.CharField(choices=[('manual', 'يدوي'), ('auto', 'تلقائي'), ('pre_restore', 'نسخة أمان')], default='manual', max_length=20, verbose_name='نوع النسخة'),
        ),
        migrations.AlterField(
            model_name='tenantcapabilities',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='core.tenant', verbose_name='المشترك'),
        ),
    ]
