# Generated by Django 4.2.7 on 2026-06-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_settings_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='EnjazIMS', max_length=100, verbose_name='اسم المنصة')),
                ('platform_tagline', models.CharField(blank=True, max_length=200, verbose_name='الشعار النصي')),
                ('platform_logo', models.ImageField(blank=True, null=True, upload_to='platform/', verbose_name='الشعار')),
                ('platform_favicon', models.ImageField(blank=True, null=True, upload_to='platform/', verbose_name='الأيقونة')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7, verbose_name='اللون الأساسي')),
                ('footer_text', models.CharField(blank=True, max_length=300, verbose_name='نص الفوتر')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('maintenance_message', models.TextField(blank=True, default='النظام قيد الصيانة حالياً. سنعود قريباً.', verbose_name='رسالة الصيانة')),
                ('announcement_active', models.BooleanField(default=False, verbose_name='تفعيل الإشعار')),
                ('announcement_text', models.CharField(blank=True, max_length=500, verbose_name='نص الإشعار')),
                ('announcement_type', models.CharField(choices=[('info', 'معلوماتي'), ('warning', 'تحذير'), ('success', 'نجاح'), ('danger', 'خطر')], default='info', max_length=10, verbose_name='نوع الإشعار')),
                ('default_currency', models.CharField(default='SDG', max_length=3, verbose_name='العملة الافتراضية')),
                ('default_timezone', models.CharField(default='Africa/Khartoum', max_length=50, verbose_name='المنطقة الزمنية الافتراضية')),
                ('default_tax_enabled', models.BooleanField(default=False, verbose_name='تفعيل الضريبة افتراضياً')),
                ('default_tax_value', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة الافتراضية %')),
                ('default_invoice_prefix', models.CharField(default='INV', max_length=10, verbose_name='بادئة الفاتورة الافتراضية')),
                ('default_trial_days', models.IntegerField(default=14, verbose_name='أيام التجربة المجانية')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات المنصة',
                'verbose_name_plural': 'إعدادات المنصة',
                'db_table': 'platform_settings',
            },
        ),
    ]
