# Generated by Django 4.2.7 on 2026-06-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_platform_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_tenant', 'مشترك جديد'), ('new_ticket', 'تذكرة دعم جديدة'), ('subscription_expiring', 'اشتراك قارب الانتهاء'), ('subscription_expired', 'اشتراك منتهٍ'), ('old_ticket', 'تذكرة مفتوحة منذ فترة'), ('general', 'عام')], default='general', max_length=30, verbose_name='النوع')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='الرابط')),
                ('ref_key', models.CharField(blank=True, max_length=120, unique=True, verbose_name='مفتاح التكرار')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'إشعار إداري',
                'verbose_name_plural': 'الإشعارات الإدارية',
                'db_table': 'admin_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
