# Generated by Django 4.2.7 on 2026-06-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fix_empty_tenant_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='invoice_color',
            field=models.CharField(default='#6366f1', max_length=7, verbose_name='لون الفاتورة'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='default_trial_days',
            field=models.IntegerField(default=30, verbose_name='أيام التجربة المجانية'),
        ),
    ]
