# Generated by Django 4.2.7 on 2026-06-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_invoice_color_to_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantcapabilities',
            name='has_variants',
        ),
    ]
