# Generated by Django 4.2.7 on 2026-06-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_tenantcapabilities_has_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='سعر العملة المحلية مقابل وحدة واحدة من العملة الصعبة', max_digits=12, verbose_name='سعر الصرف'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='exchange_rate_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث للسعر'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hard_currency',
            field=models.CharField(blank=True, default='USD', max_length=3, verbose_name='العملة الصعبة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hard_currency_mode',
            field=models.BooleanField(default=False, verbose_name='وضع العملة الصعبة'),
        ),
    ]
