# Generated by Django 4.2.7 on 2026-06-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_tenant_exchange_rate_tenant_exchange_rate_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الصرف')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='وقت التغيير')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate_history', to='core.tenant')),
            ],
            options={
                'verbose_name': 'سجل سعر الصرف',
                'verbose_name_plural': 'سجل أسعار الصرف',
                'db_table': 'exchange_rate_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
