# Generated by Django 4.2.7 on 2026-06-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_exchange_rate_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ قبول الاتفاقية'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='إصدار الاتفاقية المقبولة'),
        ),
    ]
