# Generated by Django 4.2.7 on 2026-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_terms_fields_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='print_agent_name',
            field=models.BooleanField(default=False, verbose_name='طباعة اسم المندوب في الفاتورة'),
        ),
    ]
