# Generated by Django 4.2.7 on 2026-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_settings_print_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='self_registration_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل التسجيل الذاتي'),
        ),
    ]
