# Generated by Django 4.2.7 on 2026-08-18 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_platformsettings_self_registration_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('comprehensive', 'منشور شامل'), ('problem', 'مشكلة'), ('feature', 'ميزة'), ('business_type', 'حسب نوع النشاط'), ('trust', 'ثقة وأمان'), ('objection', 'معالجة اعتراض'), ('tip', 'نصيحة تجارية'), ('comparison', 'مقارنة'), ('cta', 'دعوة مباشرة'), ('engagement', 'تفاعلي'), ('sudan_context', 'السياق السوداني')], db_index=True, default='feature', max_length=20, verbose_name='التصنيف')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('is_ai_generated', models.BooleanField(default=False, verbose_name='مولّد بالذكاء الاصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'منشور تسويقي',
                'verbose_name_plural': 'المنشورات التسويقية',
                'db_table': 'social_media_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
