# Generated by Django 4.2.7 on 2026-08-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_socialmediapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='تم النشر'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ النشر'),
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='published_channel',
            field=models.CharField(blank=True, choices=[('facebook', 'فيسبوك'), ('instagram', 'إنستقرام'), ('whatsapp', 'واتساب'), ('tiktok', 'تيك توك'), ('other', 'أخرى')], max_length=20, verbose_name='قناة النشر'),
        ),
    ]
