# Generated by Django 4.2.7 on 2026-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_socialmediapost_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='معتمد'),
        ),
    ]
