# Generated by Django 4.2.7 on 2026-09-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tenant_approved_at_tenant_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcapabilities',
            name='has_agents_module',
            field=models.BooleanField(default=False, verbose_name='المناديب ومندوبو المبيعات'),
        ),
        migrations.AddField(
            model_name='tenantcapabilities',
            name='has_pos',
            field=models.BooleanField(default=True, verbose_name='نقطة البيع (POS)'),
        ),
        migrations.AddField(
            model_name='tenantcapabilities',
            name='has_sales_invoice',
            field=models.BooleanField(default=False, verbose_name='إنشاء فاتورة مبيعات يدوياً'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='primary_color',
            field=models.CharField(default='#c9840f', max_length=7, verbose_name='اللون الأساسي'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='invoice_color',
            field=models.CharField(default='#c9840f', max_length=7, verbose_name='لون الفاتورة'),
        ),
        migrations.AlterField(
            model_name='socialmediapost',
            name='category',
            field=models.CharField(choices=[('comprehensive', 'منشور شامل'), ('problem', 'مشكلة'), ('feature', 'ميزة'), ('business_type', 'حسب نمط الصيدلية'), ('trust', 'ثقة وأمان'), ('objection', 'معالجة اعتراض'), ('tip', 'نصيحة تجارية'), ('comparison', 'مقارنة'), ('cta', 'دعوة مباشرة'), ('engagement', 'تفاعلي'), ('sudan_context', 'السياق السوداني')], db_index=True, default='feature', max_length=20, verbose_name='التصنيف'),
        ),
    ]
