# Generated by Django 4.2.7 on 2026-09-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tenantcapabilities_has_agents_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcapabilities',
            name='has_branch_stock_lookup',
            field=models.BooleanField(default=False, verbose_name='الاستعلام عن توفر الصنف بمخازن أخرى'),
        ),
        migrations.AddField(
            model_name='tenantcapabilities',
            name='has_drug_classification',
            field=models.BooleanField(default=False, verbose_name='تصنيف الأدوية (مادة فعالة، شركة مصنعة، وصفة، مخدرات)'),
        ),
        migrations.AddField(
            model_name='tenantcapabilities',
            name='has_expiry_alerts',
            field=models.BooleanField(default=False, verbose_name='تنبيهات انتهاء الصلاحية'),
        ),
        migrations.AddField(
            model_name='tenantcapabilities',
            name='has_insurance_billing',
            field=models.BooleanField(default=False, verbose_name='الفوترة عبر شركات التأمين'),
        ),
        migrations.AddField(
            model_name='tenantcapabilities',
            name='has_item_alternatives',
            field=models.BooleanField(default=False, verbose_name='بدائل الأصناف'),
        ),
    ]
