# Generated by Django 4.2.7 on 2026-09-11 09:37

from django.db import migrations, models


def fix_trial_plan_tenants(apps, schema_editor):
    """
    'trial' لم يعد قيمة صالحة لـ subscription_plan — كان يخلط بين الباقة وحالة
    الحساب. أي مشترك بهذه القيمة كان يحصل على كامل ميزات الباقة الاحترافية،
    فننقله إلى 'pro' مع تعليمه كحساب تجريبي (is_demo) للحفاظ على نفس الوصول.
    """
    Tenant = apps.get_model('core', 'Tenant')
    Tenant.objects.filter(subscription_plan='trial').update(subscription_plan='pro', is_demo=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_branch'),
    ]

    operations = [
        migrations.RunPython(fix_trial_plan_tenants, noop),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'أساسي'), ('pro', 'احترافي'), ('enterprise', 'مؤسسات')], default='basic', max_length=20, verbose_name='الباقة'),
        ),
    ]
