# Generated by Django 5.0.6 on 2026-09-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_tenant_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_name',
            field=models.CharField(default='ENJAZ', max_length=100, verbose_name='اسم المنصة'),
        ),
    ]
