# Generated by Django 4.2.7 on 2026-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_trial_days_14'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcapabilities',
            name='has_batch_numbers',
            field=models.BooleanField(default=False, verbose_name='أرقام الدُفعات'),
        ),
    ]
