# Generated by Django 4.2.7 on 2026-10-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_tenantcapabilities_has_batch_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='purchasing_mode',
            field=models.CharField(choices=[('decentralized', 'لامركزي (كل فرع يشتري لنفسه)'), ('hybrid', 'هجين (شراء مركزي من الإدارة + شراء الفروع)')], default='decentralized', max_length=15, verbose_name='نمط المشتريات'),
        ),
    ]
