# Generated by Django 4.2.7 on 2026-10-10 11:27

from django.db import migrations, models


def lock_existing_hybrid_tenants(apps, schema_editor):
    """مشترك فعّل الهجين قبل قفل النمط يبقى هجيناً ومقفولاً."""
    Tenant = apps.get_model('core', 'Tenant')
    Tenant.objects.filter(purchasing_mode='hybrid').update(purchasing_mode_locked=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_central_purchasing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='purchasing_mode_locked',
            field=models.BooleanField(default=False, verbose_name='نمط المشتريات مقفول'),
        ),
        migrations.RunPython(lock_existing_hybrid_tenants, migrations.RunPython.noop),
    ]
