# Generated by Django 4.2.7 on 2026-06-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='عملة المورد'),
        ),
    ]
