# Generated by Django 4.2.7 on 2026-06-26 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_add_terms_fields_to_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='كود المندوب')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المندوب')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('commission_type', models.CharField(choices=[('none', 'بدون عمولة'), ('percentage', 'نسبة مئوية من الفاتورة'), ('fixed', 'مبلغ ثابت لكل فاتورة')], default='none', max_length=15, verbose_name='نوع العمولة')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0, help_text='نسبة % أو مبلغ ثابت حسب نوع العمولة', max_digits=10, verbose_name='معدل العمولة')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المستحقات الافتتاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'مندوب',
                'verbose_name_plural': 'المناديب',
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('entry_type', models.CharField(choices=[('commission', 'عمولة مبيعات'), ('payment', 'دفعة للمندوب'), ('return', 'مرتجع مبيعات'), ('adjustment', 'تعديل يدوي'), ('opening', 'مستحقات افتتاحية')], max_length=15, verbose_name='نوع القيد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('entry_date', models.DateField(verbose_name='تاريخ القيد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المستحقات التراكمية')),
                ('is_reversal', models.BooleanField(default=False, verbose_name='قيد عكسي')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='agents.agent', verbose_name='المندوب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'قيد حساب مندوب',
                'verbose_name_plural': 'سجل حسابات المناديب',
                'db_table': 'agent_ledger',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'agent', '-entry_date'], name='agent_ledge_tenant__a41eaa_idx'), models.Index(fields=['reference_type', 'reference_id'], name='agent_ledge_referen_b682ae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant', 'name'], name='agents_tenant__40b40c_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant', 'phone'], name='agents_tenant__f2ad4b_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant', 'is_active'], name='agents_tenant__d9fea0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('tenant', 'code')},
        ),
    ]
