# Generated by Django 4.2.7 on 2026-06-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_user_and_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='portal_password',
            field=models.CharField(blank=True, help_text='آخر كلمة مرور مُنشأة للبوابة — للعرض الإداري فقط', max_length=64, verbose_name='كلمة مرور البوابة'),
        ),
    ]
