# Generated by Django 4.2.7 on 2026-06-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_opening_balance'),
        ('agents', '0003_add_portal_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinvoicerequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_requests', to='customers.customer', verbose_name='العميل'),
        ),
    ]
