# Generated by Django 4.2.7 on 2026-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_add_customer_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='commission_basis',
            field=models.CharField(choices=[('invoice', 'نسبة من الفاتورة'), ('collection', 'نسبة من التحصيل'), ('both', 'نسبة من الفاتورة والتحصيل معاً')], default='invoice', help_text='هل تُحسب العمولة على إجمالي الفاتورة أم على المبالغ المُحصَّلة فعلياً أم الاثنين', max_length=10, verbose_name='أساس العمولة'),
        ),
        migrations.AddField(
            model_name='agent',
            name='commission_rate_collection',
            field=models.DecimalField(decimal_places=4, default=0, help_text='يُستخدم فقط عند اختيار أساس «الفاتورة والتحصيل معاً» — معدل الشق الخاص بالتحصيل', max_digits=10, verbose_name='معدل عمولة التحصيل'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='نسبة % أو مبلغ ثابت حسب نوع العمولة (على الفاتورة، أو على التحصيل عند اختيار أساس واحد)', max_digits=10, verbose_name='معدل العمولة'),
        ),
    ]
