# Generated by Django 4.2.7 on 2026-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_commission_basis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='commission_type',
            field=models.CharField(choices=[('none', 'بدون عمولة'), ('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='none', max_length=15, verbose_name='نوع العمولة'),
        ),
    ]
