# Generated by Django 4.2.7 on 2026-04-29 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخزينة')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='الرمز')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الحالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'خزينة',
                'verbose_name_plural': 'الخزائن',
                'db_table': 'treasuries',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('movement_type', models.CharField(choices=[('receipt', 'قبض'), ('disbursement', 'صرف'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('movement_date', models.DateField(verbose_name='تاريخ الحركة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد بعد الحركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='treasury.treasury', verbose_name='الخزينة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'حركة خزينة',
                'verbose_name_plural': 'حركات الخزينة',
                'db_table': 'treasury_movements',
                'ordering': ['-movement_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'treasury', '-movement_date'], name='treasury_mo_tenant__e9fd20_idx'), models.Index(fields=['reference_type', 'reference_id'], name='treasury_mo_referen_46c158_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='treasury',
            index=models.Index(fields=['tenant', 'is_default'], name='treasuries_tenant__c30a62_idx'),
        ),
        migrations.AddIndex(
            model_name='treasury',
            index=models.Index(fields=['tenant', 'is_active'], name='treasuries_tenant__83c38e_idx'),
        ),
    ]
