# Generated by Django 4.2.7 on 2026-04-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='is_system_default',
            field=models.BooleanField(default=False, verbose_name='افتراضية نظامية'),
        ),
        migrations.AddIndex(
            model_name='treasury',
            index=models.Index(fields=['tenant', 'is_system_default'], name='treasuries_tenant__2d718d_idx'),
        ),
    ]
