# Generated by Django 4.2.7 on 2026-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_alter_treasury_tenant_alter_treasurymovement_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurymovement',
            name='movement_type',
            field=models.CharField(choices=[('receipt', 'وارد'), ('disbursement', 'صادر'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع الحركة'),
        ),
    ]
