# Generated by Django 4.2.7 on 2026-06-22 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_tenant_exchange_rate_tenant_exchange_rate_updated_at_and_more'),
        ('treasury', '0004_alter_treasurymovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='is_hard_currency',
            field=models.BooleanField(default=False, verbose_name='خزينة العملة الصعبة'),
        ),
        migrations.CreateModel(
            name='TreasuryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('from_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ المحوَّل')),
                ('to_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ المستلَم')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, help_text='وحدات العملة الهدف مقابل وحدة واحدة من عملة المصدر', max_digits=12, verbose_name='سعر الصرف')),
                ('transfer_date', models.DateField(verbose_name='تاريخ التحويل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('from_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_as_source', to='treasury.treasurymovement')),
                ('from_treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='treasury.treasury', verbose_name='من خزينة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('to_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_as_dest', to='treasury.treasurymovement')),
                ('to_treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='treasury.treasury', verbose_name='إلى خزينة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'تحويل خزينة',
                'verbose_name_plural': 'تحويلات الخزائن',
                'db_table': 'treasury_transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
    ]
