# Generated by Django 4.2.7 on 2026-06-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_treasury_currency_treasury_is_hard_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurytransfer',
            name='from_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_as_source', to='treasury.treasurymovement'),
        ),
        migrations.AlterField(
            model_name='treasurytransfer',
            name='to_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_as_dest', to='treasury.treasurymovement'),
        ),
    ]
