# Generated by Django 4.2.7 on 2026-09-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_platformsettings_platform_name'),
        ('treasury', '0006_treasury_transfer_movement_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasuries', to='core.branch', verbose_name='الفرع'),
        ),
    ]
