# Generated by Django 4.2.7 on 2026-04-28 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المخزن')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='الرمز')),
                ('stock_type', models.CharField(choices=[('main', 'مخزن رئيسي'), ('branch', 'مخزن فرع'), ('cold', 'مخزن مبرد'), ('hazardous', 'مخزن مواد خطرة'), ('transit', 'مخزن عبور / أمانات')], default='main', max_length=20, verbose_name='نوع المخزن')),
                ('branch_name', models.CharField(blank=True, help_text='يُستخدم مؤقتاً حتى يتم إنشاء تطبيق الفروع', max_length=200, verbose_name='اسم الفرع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان / الموقع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, help_text='المخزن الذي تُضاف إليه البضاعة تلقائياً عند الشراء', verbose_name='المخزن الافتراضي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
                'db_table': 'stocks',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='stocks_tenant__6d5dde_idx'), models.Index(fields=['tenant', 'is_default'], name='stocks_tenant__7091d4_idx')],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
