# Generated by Django 4.2.7 on 2026-04-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='الكمية المتاحة')),
                ('reserved_quantity', models.DecimalField(decimal_places=4, default=0, help_text='كميات مخصصة لأوامر بيع لم تُسلَّم بعد', max_digits=14, verbose_name='الكمية المحجوزة')),
                ('min_quantity', models.DecimalField(decimal_places=4, default=0, help_text='تنبيه نقص مخزون خاص بهذا المخزن (يتجاوز حد المنتج العام)', max_digits=12, verbose_name='حد الطلب الأدنى (للمخزن)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_quantities', to='items.item', verbose_name='المنتج')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='stocks.stock', verbose_name='المخزن')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'كمية مخزون',
                'verbose_name_plural': 'كميات المخزون',
                'db_table': 'stock_quantities',
                'indexes': [models.Index(fields=['tenant', 'stock'], name='stock_quant_tenant__3086a3_idx'), models.Index(fields=['tenant', 'item'], name='stock_quant_tenant__eb8b11_idx'), models.Index(fields=['tenant', 'stock', 'quantity'], name='stock_quant_tenant__cd2430_idx')],
                'unique_together': {('tenant', 'stock', 'item')},
            },
        ),
    ]
