# Generated by Django 4.2.7 on 2026-04-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='مخزن نظامي يُنشأ تلقائياً مع الاشتراك ولا يمكن حذفه.', verbose_name='افتراضي نظامي'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['tenant', 'is_system_default'], name='stocks_tenant__232975_idx'),
        ),
    ]
