# Generated by Django 4.2.7 on 2026-05-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_is_system_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_type',
            field=models.CharField(choices=[('main', 'مخزن رئيسي'), ('branch', 'مخزن فرع')], default='main', max_length=20, verbose_name='نوع المخزن'),
        ),
    ]
