# Generated by Django 4.2.7 on 2026-05-21 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
        ('core', '0005_alter_tenant_currency'),
        ('stocks', '0005_stock_transfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('stocktake_number', models.CharField(blank=True, max_length=30, verbose_name='رقم الجرد')),
                ('stocktake_date', models.DateField(verbose_name='تاريخ الجرد')),
                ('status', models.CharField(choices=[('draft', 'جاري الجرد'), ('confirmed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=12, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='stocks.stock', verbose_name='المخزن')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'جرد مخزون',
                'verbose_name_plural': 'جرد المخزون',
                'db_table': 'stocktakes',
                'ordering': ['-stocktake_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('system_quantity', models.DecimalField(decimal_places=4, default=0, help_text='الكمية في النظام عند بدء الجرد', max_digits=12, verbose_name='كمية النظام')),
                ('counted_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='الكمية المعدودة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_lines', to='items.item', verbose_name='المنتج')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stocks.stocktake', verbose_name='الجرد')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'بند جرد',
                'verbose_name_plural': 'بنود الجرد',
                'db_table': 'stocktake_lines',
                'unique_together': {('stocktake', 'item')},
            },
        ),
        migrations.AddIndex(
            model_name='stocktake',
            index=models.Index(fields=['tenant', 'status'], name='stocktakes_tenant__df23ca_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktake',
            index=models.Index(fields=['tenant', '-stocktake_date'], name='stocktakes_tenant__2e5d25_idx'),
        ),
    ]
