# Generated by Django 4.2.7 on 2026-06-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_manufacturingorder_tenant_alter_stock_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockquantity',
            name='opening_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='الكمية الافتتاحية المُدخلة — لا تتأثر بحركات البيع والشراء', max_digits=14, verbose_name='الكمية الافتتاحية'),
        ),
    ]
