# Generated by Django 4.2.7 on 2026-09-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_branch'),
        ('stocks', '0009_opening_quantity_and_correction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='branch_name',
            field=models.CharField(blank=True, help_text='حقل قديم قبل إضافة موديل الفرع الحقيقي — يُستخدم كنسخة احتياطية فقط', max_length=200, verbose_name='اسم الفرع (قديم)'),
        ),
    ]
