# Generated by Django 4.2.7 on 2026-09-09 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_item_is_insurance_excluded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_branch'),
        ('stocks', '0010_stock_branch_alter_stock_branch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDestruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('destruction_number', models.CharField(blank=True, max_length=30, verbose_name='رقم السجل')),
                ('destruction_date', models.DateField(verbose_name='تاريخ الإتلاف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='draft', max_length=12, verbose_name='الحالة')),
                ('reason', models.CharField(choices=[('expired', 'منتهي الصلاحية'), ('damaged', 'تالف'), ('recalled', 'مسحوب من الشركة المصنعة'), ('other', 'أخرى')], default='expired', max_length=20, verbose_name='السبب')),
                ('witness_name', models.CharField(blank=True, help_text='اسم الشخص الذي شهد عملية الإتلاف (متطلب رقابي شائع)', max_length=200, verbose_name='اسم الشاهد / المسؤول')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم مرجعي / محضر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_destructions', to=settings.AUTH_USER_MODEL, verbose_name='أُكِّد بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destructions', to='stocks.stock', verbose_name='المخزن')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل إتلاف',
                'verbose_name_plural': 'سجلات الإتلاف',
                'db_table': 'stock_destructions',
                'ordering': ['-destruction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockDestructionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('batch_number_snapshot', models.CharField(blank=True, max_length=100, verbose_name='رقم الدفعة')),
                ('expiry_date_snapshot', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية')),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة الوحدة')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='ملاحظات')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destruction_lines', to='items.itembatch', verbose_name='الدفعة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('destruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stocks.stockdestruction', verbose_name='سجل الإتلاف')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destruction_lines', to='items.item', verbose_name='المنتج')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'بند إتلاف',
                'verbose_name_plural': 'بنود الإتلاف',
                'db_table': 'stock_destruction_lines',
            },
        ),
        migrations.AddIndex(
            model_name='stockdestruction',
            index=models.Index(fields=['tenant', 'status'], name='stock_destr_tenant__d9952b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdestruction',
            index=models.Index(fields=['tenant', '-destruction_date'], name='stock_destr_tenant__c4ef2f_idx'),
        ),
    ]
