# Generated by Django 4.2.7 on 2026-09-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_stockdestruction_stockdestructionline_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockquantity',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='stockquantity_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='stockquantity',
            constraint=models.CheckConstraint(check=models.Q(('reserved_quantity__gte', 0)), name='stockquantity_reserved_quantity_gte_0'),
        ),
    ]
