# Generated by Django 5.0.6 on 2026-09-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_stockquantity_stockquantity_quantity_gte_0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_type',
        ),
    ]
