# Generated by Django 4.2.7 on 2026-10-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_remove_stock_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_central',
            field=models.BooleanField(default=False, help_text='مخزن الإدارة المركزية: بلا فرع، للشراء المركزي والتوزيع على الفروع فقط.', verbose_name='مخزن مركزي'),
        ),
    ]
