# Generated by Django 4.2.7 on 2026-10-10 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_alter_item_track_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_central_purchasing'),
        ('stocks', '0014_central_purchasing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('shipment_number', models.CharField(blank=True, max_length=30, verbose_name='رقم الشحنة')),
                ('shipment_date', models.DateField(verbose_name='تاريخ الشحنة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_transit', 'في الطريق'), ('received', 'تم الاستلام'), ('cancelled', 'ملغية')], default='draft', max_length=12, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('has_difference', models.BooleanField(default=False, verbose_name='فيها فرق استلام')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستلام')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_shipments', to='core.branch', verbose_name='الفرع المستلِم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('from_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_out', to='stocks.stock', verbose_name='من المخزن المركزي')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_shipments', to=settings.AUTH_USER_MODEL, verbose_name='استلمها')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('to_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_in', to='stocks.stock', verbose_name='إلى مخزن الفرع')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'شحنة مخزن مركزي',
                'verbose_name_plural': 'شحنات المخزن المركزي',
                'db_table': 'stock_shipments',
                'ordering': ['-shipment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('quantity_sent', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية المرسلة')),
                ('quantity_received', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='الكمية المستلَمة')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='تكلفة الوحدة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='items.item', verbose_name='المنتج')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stocks.shipment', verbose_name='الشحنة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'بند شحنة',
                'verbose_name_plural': 'بنود الشحنات',
                'db_table': 'stock_shipment_lines',
            },
        ),
        migrations.CreateModel(
            name='ShipmentLineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الدفعة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('quantity_sent', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية المرسلة')),
                ('quantity_received', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='الكمية المستلَمة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stocks.shipmentline', verbose_name='البند')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.itembatch', verbose_name='الدفعة المصدر')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'دفعة بند شحنة',
                'verbose_name_plural': 'دفعات بنود الشحنات',
                'db_table': 'stock_shipment_line_batches',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'status'], name='stock_shipm_tenant__ba3fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='stock_shipm_tenant__11edc8_idx'),
        ),
    ]
