# Generated by Django 4.2.7 on 2026-10-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_central_purchasing'),
        ('stocks', '0015_shipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='direction',
            field=models.CharField(choices=[('to_branch', 'توزيع من المركزي إلى الفرع'), ('to_central', 'مرتجع من الفرع إلى المركزي')], default='to_branch', max_length=10, verbose_name='الاتجاه'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_shipments', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='from_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_out', to='stocks.stock', verbose_name='من المخزن'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_in', to='stocks.stock', verbose_name='إلى المخزن'),
        ),
    ]
