# Generated by Django 4.2.7 on 2026-10-10 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def mark_inter_branch_drafts(apps, schema_editor):
    """المسودات القائمة بين فرعين تتبع دورة الإرسال والاعتماد بدل التأكيد الفوري."""
    StockTransfer = apps.get_model('stocks', 'StockTransfer')
    drafts = StockTransfer.objects.filter(
        status='draft', from_stock__branch__isnull=False, to_stock__branch__isnull=False,
    ).exclude(from_stock__branch=models.F('to_stock__branch'))
    drafts.update(is_inter_branch=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_purchasing_mode_locked'),
        ('items', '0015_alter_item_track_batch'),
        ('stocks', '0016_shipment_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='has_difference',
            field=models.BooleanField(default=False, verbose_name='فيه فرق استلام'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='is_inter_branch',
            field=models.BooleanField(default=False, verbose_name='بين فرعين'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستلام'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stock_transfers', to=settings.AUTH_USER_MODEL, verbose_name='استلمه'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تسوية الناقص'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_stock_transfers', to=settings.AUTH_USER_MODEL, verbose_name='سوّى الناقص'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='shortage_destruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_shortages', to='stocks.stockdestruction', verbose_name='سجل إتلاف الناقص'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='shortage_status',
            field=models.CharField(choices=[('none', 'لا يوجد'), ('pending', 'بانتظار التسوية'), ('restocked', 'أُعيد لمخزن الفرع المحوِّل'), ('written_off', 'شُطب تالفاً على الفرع المحوِّل')], default='none', max_length=12, verbose_name='حالة الناقص'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='quantity_received',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='الكمية المستلَمة'),
        ),
        migrations.AddField(
            model_name='stocktransferline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة الوحدة'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('in_transit', 'في الطريق'), ('received', 'تم الاستلام'), ('cancelled', 'ملغي')], default='draft', max_length=12, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='StockTransferLineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الدفعة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('quantity_sent', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='المرسلة')),
                ('quantity_received', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='المستلَمة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stocks.stocktransferline', verbose_name='البند')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.itembatch', verbose_name='الدفعة المصدر')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'دفعة بند تحويل',
                'verbose_name_plural': 'دفعات بنود التحويل',
                'db_table': 'stock_transfer_line_batches',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(mark_inter_branch_drafts, migrations.RunPython.noop),
    ]
