# Generated by Django 5.0.6 on 2026-09-15 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_label', models.CharField(blank=True, max_length=200, verbose_name='مصدر القائمة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('extracting', 'جاري الاستخراج'), ('reviewing', 'قيد المراجعة'), ('committing', 'جاري الاعتماد'), ('committed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('header_mapping', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دفعة استيراد للكتالوج',
                'verbose_name_plural': 'دفعات استيراد الكتالوج',
                'db_table': 'catalog_import_batches',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.mastercategory', verbose_name='التصنيف الرئيسي')),
            ],
            options={
                'verbose_name': 'تصنيف رئيسي',
                'verbose_name_plural': 'التصنيفات الرئيسية',
                'db_table': 'catalog_master_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=300, verbose_name='الاسم العلمي / المادة الفعالة')),
                ('generic_name_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=300)),
                ('dosage_form', models.CharField(blank=True, max_length=100, verbose_name='الشكل الصيدلاني')),
                ('dosage_form_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=100)),
                ('strength', models.CharField(blank=True, max_length=100, verbose_name='التركيز')),
                ('strength_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=100)),
                ('default_unit_name', models.CharField(blank=True, max_length=50, verbose_name='الوحدة المقترحة')),
                ('default_dosage_conversion', models.JSONField(blank=True, default=list, help_text='مثال: [{"name": "شريط", "factor": 10}, {"name": "علبة", "factor": 100}]', verbose_name='تحويلات الوحدات المقترحة')),
                ('requires_prescription', models.BooleanField(default=False, verbose_name='يُصرف بوصفة طبية')),
                ('is_controlled_substance', models.BooleanField(default=False, verbose_name='خاضع للرقابة / مخدرات')),
                ('is_insurance_excluded', models.BooleanField(default=False, verbose_name='غير مغطى بالتأمين')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('merged', 'مدموج'), ('deprecated', 'متوقف')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs', to='catalog.mastercategory', verbose_name='التصنيف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_drugs_created', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='catalog.masterdrug', verbose_name='مدموج في')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_drugs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دواء (كتالوج رئيسي)',
                'verbose_name_plural': 'الكتالوج الرئيسي للأدوية',
                'db_table': 'catalog_master_drugs',
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('match_status', models.CharField(choices=[('pending', 'بانتظار المعالجة'), ('new', 'دواء جديد'), ('duplicate_exact', 'مطابق تماماً'), ('duplicate_fuzzy', 'يحتاج مراجعة'), ('needs_review', 'يحتاج مراجعة يدوية'), ('rejected', 'مرفوض'), ('committed', 'تم الاعتماد')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='catalog.catalogimportbatch')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_rows_reviewed', to=settings.AUTH_USER_MODEL)),
                ('matched_master_drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='catalog.masterdrug')),
            ],
            options={
                'verbose_name': 'صف استيراد كتالوج',
                'verbose_name_plural': 'صفوف استيراد الكتالوج',
                'db_table': 'catalog_import_rows',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='MasterDrugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=300, verbose_name='الاسم التجاري')),
                ('trade_name_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=300)),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='الشركة المصنعة')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='الباركود')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الاسم الأساسي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_drug_aliases_created', to=settings.AUTH_USER_MODEL)),
                ('master_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.masterdrug')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases_created', to='catalog.catalogimportbatch')),
            ],
            options={
                'verbose_name': 'اسم تجاري',
                'verbose_name_plural': 'الأسماء التجارية',
                'db_table': 'catalog_master_drug_aliases',
                'ordering': ['trade_name'],
            },
        ),
        migrations.AddIndex(
            model_name='masterdrug',
            index=models.Index(fields=['generic_name_normalized', 'dosage_form_normalized', 'strength_normalized'], name='catalog_mas_generic_f324ac_idx'),
        ),
        migrations.AddIndex(
            model_name='masterdrug',
            index=models.Index(fields=['status'], name='catalog_mas_status_20f2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogimportrow',
            index=models.Index(fields=['batch', 'match_status'], name='catalog_imp_batch_i_1844c0_idx'),
        ),
        migrations.AddIndex(
            model_name='masterdrugalias',
            index=models.Index(fields=['master_drug'], name='catalog_mas_master__9e3d90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='masterdrugalias',
            unique_together={('trade_name_normalized', 'manufacturer')},
        ),
    ]
