# Generated by Django 5.0.6 on 2026-09-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdrug',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='masterdrug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/master_drugs/', verbose_name='صورة تعريفية'),
        ),
        migrations.AddField(
            model_name='masterdrug',
            name='item_type',
            field=models.CharField(default='product', max_length=20, verbose_name='نوع الصنف'),
        ),
        migrations.AddField(
            model_name='masterdrug',
            name='track_batch',
            field=models.BooleanField(default=True, verbose_name='تتبع رقم الدفعة (مقترح)'),
        ),
        migrations.AddField(
            model_name='masterdrug',
            name='track_expiry',
            field=models.BooleanField(default=True, verbose_name='تتبع تاريخ الانتهاء (مقترح)'),
        ),
        migrations.AddField(
            model_name='masterdrug',
            name='track_serial',
            field=models.BooleanField(default=False, verbose_name='تتبع الرقم التسلسلي (مقترح)'),
        ),
    ]
