# Generated by Django 5.0.6 on 2026-09-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_masterdrug_description_masterdrug_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterdrugalias',
            unique_together={('trade_name_normalized', 'manufacturer', 'master_drug')},
        ),
        migrations.AddField(
            model_name='masterdrugalias',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, verbose_name='بلد المنشأ'),
        ),
        migrations.AddField(
            model_name='masterdrugalias',
            name='pack_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='حجم العبوة'),
        ),
        migrations.AddField(
            model_name='masterdrugalias',
            name='sudan_agent',
            field=models.CharField(blank=True, max_length=200, verbose_name='الوكيل أو الموزع في السودان'),
        ),
    ]
