# Generated by Django 5.0.6 on 2026-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_masterdrugalias_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdrug',
            name='strength',
            field=models.CharField(blank=True, max_length=300, verbose_name='التركيز'),
        ),
        migrations.AlterField(
            model_name='masterdrugalias',
            name='pack_size',
            field=models.CharField(blank=True, max_length=300, verbose_name='حجم العبوة'),
        ),
    ]
