# Generated by Django 4.2.7 on 2026-05-01 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0003_purchase_returns'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseinvoice',
            new_name='purchase_in_tenant__d1f248_idx',
            old_name='purchase_in_tenant__f25795_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseinvoice',
            new_name='purchase_in_tenant__5884c4_idx',
            old_name='purchase_in_tenant__6ab724_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaseinvoice',
            new_name='purchase_in_tenant__6fdee6_idx',
            old_name='purchase_in_tenant__6a6ec1_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasepayment',
            new_name='purchase_pa_tenant__04c87b_idx',
            old_name='purchase_pa_tenant__fcd06f_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasereturn',
            new_name='purchase_re_tenant__b92f60_idx',
            old_name='purchase_re_tenant__f59f99_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasereturn',
            new_name='purchase_re_tenant__d9cc2b_idx',
            old_name='purchase_re_tenant__8e35cd_idx',
        ),
        migrations.RenameIndex(
            model_name='purchasereturn',
            new_name='purchase_re_tenant__86b17d_idx',
            old_name='purchase_re_tenant__791a93_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierledger',
            new_name='supplier_le_tenant__78f97d_idx',
            old_name='supplier_le_tenant__684fab_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierledger',
            new_name='supplier_le_referen_311d4f_idx',
            old_name='supplier_le_referen_42d5aa_idx',
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AlterField(
            model_name='supplierledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='supplierledger',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
    ]
