# Generated by Django 4.2.7 on 2026-05-21 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stocktake'),
        ('core', '0005_alter_tenant_currency'),
        ('items', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0005_purchaseinvoiceline_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('rfq_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الطلب')),
                ('rfq_date', models.DateField(verbose_name='تاريخ الطلب')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مُرسَل للمورد'), ('received', 'استُلم الرد'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('converted', 'مُحوَّل لأمر شراء'), ('cancelled', 'ملغى')], default='draft', max_length=12, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('terms', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي المقتبَس')),
                ('converted_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_rfq', to='purchases.purchaseinvoice', verbose_name='أمر الشراء المُحوَّل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_rfqs', to='stocks.stock', verbose_name='المخزن')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_rfqs', to='suppliers.supplier', verbose_name='المورد')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'طلب عرض أسعار',
                'verbose_name_plural': 'طلبات عروض الأسعار',
                'db_table': 'purchase_rfqs',
                'ordering': ['-rfq_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRFQLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('requested_quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية المطلوبة')),
                ('quoted_price', models.DecimalField(decimal_places=2, default=0, help_text='يُملأ عند استلام رد المورد', max_digits=14, verbose_name='السعر المقتبَس')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي السطر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='items.item', verbose_name='المنتج')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaserfq', verbose_name='طلب العرض')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='العميل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'بند طلب عرض',
                'verbose_name_plural': 'بنود طلب العرض',
                'db_table': 'purchase_rfq_lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserfq',
            index=models.Index(fields=['tenant', 'status'], name='purchase_rf_tenant__862ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserfq',
            index=models.Index(fields=['tenant', '-rfq_date'], name='purchase_rf_tenant__72ff08_idx'),
        ),
    ]
