# Generated by Django 4.2.7 on 2026-06-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_settings_options_alter_tenant_options_and_more'),
        ('purchases', '0007_purchaseinvoiceline_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='purchasereturnline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='purchaserfq',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='purchaserfqline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
        migrations.AlterField(
            model_name='supplierledger',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
    ]
