# Generated by Django 4.2.7 on 2026-06-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_alter_purchaseinvoice_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierledger',
            name='is_reversal',
            field=models.BooleanField(default=False, verbose_name='قيد عكسي'),
        ),
    ]
