# Generated by Django 4.2.7 on 2026-09-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('purchases', '0010_add_hc_fields_to_ledgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='الحساب البنكي الصادر منه الجزء البنكي من أمر الشراء', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='bank_accounts.bankaccount', verbose_name='الحساب البنكي'),
        ),
    ]
