# Generated by Django 4.2.7 on 2026-06-16 10:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_add_invoice_color_to_settings'),
        ('treasury', '0003_alter_treasury_tenant_alter_treasurymovement_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('employee_id', models.CharField(blank=True, max_length=30, verbose_name='رقم الموظف')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='المسمى الوظيفي')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='القسم')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='الصورة')),
                ('salary_type', models.CharField(choices=[('fixed', 'راتب ثابت'), ('hourly', 'بالساعة'), ('daily', 'بالأيام')], default='fixed', max_length=20, verbose_name='نوع الراتب')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الراتب الأساسي')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'db_table': 'employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('period_start', models.DateField(verbose_name='من')),
                ('period_end', models.DateField(verbose_name='إلى')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الراتب الأساسي')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الحوافز')),
                ('advances_deducted', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='السلف المخصومة')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='خصومات أخرى')),
                ('deductions_notes', models.TextField(blank=True, verbose_name='تفاصيل الخصومات')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('paid', 'مدفوع'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='employees.employee', verbose_name='الموظف')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.treasury', verbose_name='الخزينة')),
                ('treasury_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_salary', to='treasury.treasurymovement', verbose_name='حركة الخزينة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'كشف راتب',
                'verbose_name_plural': 'كشوف الرواتب',
                'db_table': 'employee_salary_payments',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('type', models.CharField(choices=[('bonus', 'حافز'), ('deduction', 'خصم')], default='bonus', max_length=20, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('payout', models.CharField(choices=[('immediate', 'فوري'), ('with_salary', 'مع الراتب')], default='with_salary', max_length=20, verbose_name='طريقة الصرف')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='employees.employee', verbose_name='الموظف')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.treasury', verbose_name='الخزينة')),
                ('treasury_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_incentive', to='treasury.treasurymovement', verbose_name='حركة الخزينة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'حافز / خصم',
                'verbose_name_plural': 'الحوافز والخصومات',
                'db_table': 'employee_incentives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('pending', 'قائمة'), ('deducted', 'مخصومة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='employees.employee', verbose_name='الموظف')),
                ('salary_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_items', to='employees.employeesalarypayment', verbose_name='كشف الراتب')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.treasury', verbose_name='الخزينة')),
                ('treasury_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_advance', to='treasury.treasurymovement', verbose_name='حركة الخزينة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'سلفة موظف',
                'verbose_name_plural': 'سلف الموظفين',
                'db_table': 'employee_advances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employeesalarypayment',
            index=models.Index(fields=['tenant', 'status'], name='employee_sa_tenant__9aebb8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalarypayment',
            index=models.Index(fields=['tenant', 'employee'], name='employee_sa_tenant__458b80_idx'),
        ),
        migrations.AddIndex(
            model_name='employeesalarypayment',
            index=models.Index(fields=['tenant', 'period_start'], name='employee_sa_tenant__16f9be_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeincentive',
            index=models.Index(fields=['tenant', 'type'], name='employee_in_tenant__eae7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeincentive',
            index=models.Index(fields=['tenant', 'status'], name='employee_in_tenant__becd91_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeincentive',
            index=models.Index(fields=['tenant', 'employee'], name='employee_in_tenant__5e16cf_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeadvance',
            index=models.Index(fields=['tenant', 'status'], name='employee_ad_tenant__04fecb_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeadvance',
            index=models.Index(fields=['tenant', 'employee'], name='employee_ad_tenant__7be02c_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'is_active'], name='employees_tenant__6ef9d1_idx'),
        ),
    ]
