# Generated by Django 4.2.7 on 2026-06-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_alter_treasury_tenant_alter_treasurymovement_tenant'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadvance',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الحوالة'),
        ),
        migrations.AddField(
            model_name='employeeadvance',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي')], default='cash', max_length=10, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='employeeincentive',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الحوالة'),
        ),
        migrations.AddField(
            model_name='employeeincentive',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي')], default='cash', max_length=10, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='employeesalarypayment',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الحوالة'),
        ),
        migrations.AddField(
            model_name='employeesalarypayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي')], default='cash', max_length=10, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='employeeadvance',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.treasury', verbose_name='الخزينة / الحساب'),
        ),
        migrations.AlterField(
            model_name='employeeincentive',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.treasury', verbose_name='الخزينة / الحساب'),
        ),
        migrations.AlterField(
            model_name='employeesalarypayment',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.treasury', verbose_name='الخزينة / الحساب'),
        ),
    ]
