# Generated by Django 4.2.7 on 2026-06-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_add_payment_method_bank_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفين'},
        ),
    ]
