# Generated by Django 4.2.7 on 2026-09-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('employees', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadvance',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accounts.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='employeeadvance',
            name='bank_account_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_advance', to='bank_accounts.bankaccountmovement', verbose_name='حركة الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='employeeincentive',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accounts.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='employeeincentive',
            name='bank_account_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_incentive', to='bank_accounts.bankaccountmovement', verbose_name='حركة الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='employeesalarypayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_accounts.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='employeesalarypayment',
            name='bank_account_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_salary', to='bank_accounts.bankaccountmovement', verbose_name='حركة الحساب البنكي'),
        ),
    ]
