# Generated by Django 4.2.7 on 2026-09-14 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeeadvance_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeincentive',
            name='salary_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_items', to='employees.employeesalarypayment', verbose_name='كشف الراتب'),
        ),
    ]
