# Generated by Django 4.2.7 on 2026-09-12 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0025_alter_tenant_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasury', '0006_treasury_transfer_movement_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='اسم البنك')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='الآيبان')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('currency', models.CharField(blank=True, default='', max_length=3, verbose_name='العملة')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الحالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
                'db_table': 'bank_accounts',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccountMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('movement_type', models.CharField(choices=[('receipt', 'وارد'), ('disbursement', 'صادر'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('movement_date', models.DateField(verbose_name='تاريخ الحركة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد بعد الحركة')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='bank_accounts.bankaccount', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'حركة حساب بنكي',
                'verbose_name_plural': 'حركات الحسابات البنكية',
                'db_table': 'bank_account_movements',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryBankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('direction', models.CharField(choices=[('treasury_to_bank', 'من الخزينة إلى الحساب البنكي'), ('bank_to_treasury', 'من الحساب البنكي إلى الخزينة')], max_length=20, verbose_name='الاتجاه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('transfer_date', models.DateField(verbose_name='تاريخ التحويل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_transfers', to='bank_accounts.bankaccount', verbose_name='الحساب البنكي')),
                ('bank_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasury_transfer', to='bank_accounts.bankaccountmovement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfers', to='treasury.treasury', verbose_name='الخزينة')),
                ('treasury_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer', to='treasury.treasurymovement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'تحويل خزينة / حساب بنكي',
                'verbose_name_plural': 'تحويلات الخزينة والحسابات البنكية',
                'db_table': 'treasury_bank_transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('from_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ المحوَّل')),
                ('to_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ المستلَم')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, help_text='وحدات العملة الهدف مقابل وحدة واحدة من عملة المصدر', max_digits=12, verbose_name='سعر الصرف')),
                ('transfer_date', models.DateField(verbose_name='تاريخ التحويل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('from_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='bank_accounts.bankaccount', verbose_name='من حساب')),
                ('from_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_as_source', to='bank_accounts.bankaccountmovement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك')),
                ('to_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='bank_accounts.bankaccount', verbose_name='إلى حساب')),
                ('to_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_as_dest', to='bank_accounts.bankaccountmovement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'تحويل بين حسابات بنكية',
                'verbose_name_plural': 'تحويلات الحسابات البنكية',
                'db_table': 'bank_account_transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccountmovement',
            index=models.Index(fields=['tenant', 'bank_account', '-movement_date'], name='bank_accoun_tenant__ab6126_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountmovement',
            index=models.Index(fields=['reference_type', 'reference_id'], name='bank_accoun_referen_45dce7_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['tenant', 'is_default'], name='bank_accoun_tenant__ffa50f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['tenant', 'is_active'], name='bank_accoun_tenant__ce9edb_idx'),
        ),
    ]
