# Generated by Django 4.2.7 on 2026-09-23 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_accounts', '0002_bankaccount_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_head_office',
            field=models.BooleanField(default=False, verbose_name='حساب الإدارة المركزية'),
        ),
        migrations.AddField(
            model_name='bankaccounttransfer',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء'),
        ),
        migrations.AddField(
            model_name='bankaccounttransfer',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أُلغي بواسطة'),
        ),
        migrations.AddField(
            model_name='bankaccounttransfer',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='ملغى'),
        ),
    ]
