# Generated by Django 4.2.7 on 2026-09-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('expenses', '0003_alter_expense_tenant_alter_expensecategory_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='bank_accounts.bankaccount', verbose_name='الحساب البنكي'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bank_account_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='bank_accounts.bankaccountmovement', verbose_name='حركة الحساب البنكي'),
        ),
    ]
