# Generated by Django 4.2.7 on 2026-09-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_platformsettings_platform_name'),
        ('expenses', '0004_expense_bank_account_expense_bank_account_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.branch', verbose_name='الفرع'),
        ),
    ]
