# Generated by Django 4.2.7 on 2026-06-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_settings_options_alter_tenant_options_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'مخزون منخفض'), ('overdue_invoice', 'فاتورة متأخرة'), ('rfq_expiry', 'انتهاء صلاحية طلب السعر'), ('transfer_done', 'اكتمال تحويل مخزون'), ('stocktake_done', 'اكتمال جرد مخزون'), ('online_order', 'طلب جديد من المتجر'), ('general', 'إشعار عام')], default='general', max_length=25, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='المشترك'),
        ),
    ]
