# Generated by Django 4.2.7 on 2026-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'مخزون منخفض'), ('overdue_invoice', 'فاتورة متأخرة'), ('rfq_expiry', 'انتهاء صلاحية طلب السعر'), ('transfer_done', 'اكتمال تحويل مخزون'), ('stocktake_done', 'اكتمال جرد مخزون'), ('online_order', 'طلب جديد من المتجر'), ('agent_request', 'طلب مندوب جديد'), ('general', 'إشعار عام')], default='general', max_length=25, verbose_name='النوع'),
        ),
    ]
